// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });
import "@/styles/normalize.css"
import "@/styles/globals.css"
import Header from "@/components/Header"
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}